name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # จำลอง MongoDB ขึ้นมาเพื่อให้ Backend สามารถต่อ Database ได้ตอนรันเทส
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [18.x, 20.x] # ใช้ Node.js เวอร์ชันหลักเพื่อให้รันเร็วขึ้น

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # รันเทสของคุณ
    - name: Run Postman Tests
      run: |
        newman run __test__/BackendProjectTestcaseFirstSprint.postman_collection \
        --env-var "URL=https://backendmatikanetannhauser.vercel.app"